### ISSUE TITLE
Revised polygons

### ISSUE THREAD

**Issue by jw35** [ijl20/tfc_server#7]
Consider revising the Histon Rd and Milton road polygons as suggested in these Forum posts:

https://smartcambridge.org/csn/forum/forum/traffic-2/topic/histon-rd-32/
https://smartcambridge.org/csn/forum/forum/traffic-2/topic/milton-rd-8/

**Comment by abrahammartin** [comment]
I'd suggest modifying Madingley Road as well as it is only measuring M11 onwards whereas the traffic problems are always before M11 from Madingley Mulch

**Comment by jw35** [comment]
Closed by #11
